---
- name: WinRM と Dhcp サービスの状態を取得
  changed_when: false
  ansible.windows.win_shell: |
    $services = @('WinRM', 'Dhcp')
    $result = foreach ($svcName in $services) {
      $svc = Get-Service -Name $svcName
      [PSCustomObject]@{
        Name = $svc.Name
        DisplayName = $svc.DisplayName
        Status = $svc.Status.ToString()
      }
    }
    $result | ConvertTo-Json -Depth 2
  register: service_raw

- name: JSON を構造化
  set_fact:
    service_info: "{{ service_raw.stdout | from_json }}"

- name: サービス状態を表示
  debug:
    var: service_info

- name: サービスが稼働していることを確認
  assert:
    that:
      - item.Status == "Running"
    fail_msg: "{{ item.Name }} サービスは稼働していません（状態: {{ item.Status }}）"
    success_msg: "{{ item.Name }} サービスは稼働しています"
  loop: "{{ service_info }}"
  loop_control:
    label: "{{ item.Name }}"

